apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-config
  namespace: logplex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-config
  template:
    metadata:
      labels:
        app: redis-config
    spec:
      containers:
      - name: redis
        image: redis:2.6
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-config
  namespace: logplex
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis-config
